import turtle
wn = turtle.Screen()
wn.bgcolor("black")
wn.title("Hello, Josh!")
Josh=turtle.Turtle()
Josh.color ("blue")
Josh.pensize(5)

Josh.right(90)
Josh.forward(150)
Josh.right(60)
Josh.forward(50)
Josh.right(60)
Josh.forward(50)
Josh.right(180)
Josh.forward(50)
Josh.left(30)
Josh.forward(180)
Josh.left(60)
Josh.forward(50)
Josh.left(60)
Josh.forward(50)
Josh.left(60)
Josh.forward(50)
Josh.left(60)
Josh.forward(50)
Josh.left(60)
Josh.forward(50)

